//
// Created by boris on 11/19/2021.
//

#ifndef VENGINE3D_VE_MOUSEKEY_HPP
#define VENGINE3D_VE_MOUSEKEY_HPP

#define VE_MOUSE_BUTTON_1         0
#define VE_MOUSE_BUTTON_2         1
#define VE_MOUSE_BUTTON_3         2
#define VE_MOUSE_BUTTON_4         3
#define VE_MOUSE_BUTTON_5         4
#define VE_MOUSE_BUTTON_6         5
#define VE_MOUSE_BUTTON_7         6
#define VE_MOUSE_BUTTON_8         7
#define VE_MOUSE_BUTTON_LAST      VE_MOUSE_BUTTON_8
#define VE_MOUSE_BUTTON_LEFT      VE_MOUSE_BUTTON_1
#define VE_MOUSE_BUTTON_RIGHT     VE_MOUSE_BUTTON_2
#define VE_MOUSE_BUTTON_MIDDLE    VE_MOUSE_BUTTON_3

#endif //VENGINE3D_VE_MOUSEKEY_HPP
